# MODIFICACIONES A LA TABLA ROLES_FUNCIONES.
ALTER TABLE roles_funciones
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE roles_funciones
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;