# MODIFICACIONES A LA TABLA Marcas.
ALTER TABLE marcas
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE marcas
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

# EVITAR DUPLICADOS EN LOS NOMBRES DE LAS MARCAS
ALTER TABLE marcas ADD UNIQUE (ma_nombre);

SELECT * FROM marcas WHERE ma_nombre = 'hola mundo';